### PR TITLE
Fix on_flow_arrival handler bugs

### PR DESCRIPTION
**Pull request by MagnusS**
Fix on_flow_arrival to not swap src/dst when processing SYNs, move on_flow_arrival default handler to the input function so listen_tcpv4 works without a previous call to listen_tcpv4_flow. See individual commits for more details.

This should fix the tests and allow existing mirage code to use the stack unmodified.

cc @djs55 @yomimono

### CODE REVIEW

**Comment by MagnusS** [comment]
Moving the on_flow_arrival wrapper to the input function also means that you can no longer `Reject on behalf of the Hashtbl listeners by setting the handler directly (without calling listen_tcpv4_flow) - but it doesn't look like it is ever used in this way?

**Comment by MagnusS** [comment]
Moving the on_flow_arrival wrapper to the input function also means that you can no longer `Reject on behalf of the Hashtbl listeners by setting the handler directly (without calling listen_tcpv4_flow) - but it doesn't look like it is ever used in this way?

**Comment by djs55** [comment]
Thanks! I strongly suspect that the flipping of `src` and `dst` is responsible for the craziness in `vpnkit` where some code is using `src` but then further down the same function near identical code is using `dst`. So I think this will require some tweaks to `vpnkit` but this is almost certainly a good thing!

**Comment by djs55** [comment]
Merged into the misleadingly-named branch: https://github.com/djs55/mirage-tcpip/tree/3.0.0-beta7

**Pull request closed without merging**
